### ISSUE TITLE
接口好像失效了 

### ISSUE THREAD

**Issue by popy32** [YaoZeyuan/zhihuhelp_with_node#11]
接口好像失效了 1.0和2.1版本都有这个问题

所有内容均无法抓取

```bash
2019-02-25 10:23:50.271: [GenerateCollection] TypeError: Cannot read property 'question' of undefined
at Function.generateSingleItemElement (C:\Users\lin\AppData\Local\Programs\zhihuhelp\resources\app\dist\view\answer.js:29:73)
at Function.renderInSinglePage (C:\Users\lin\AppData\Local\Programs\zhihuhelp\resources\app\dist\view\answer.js:54:34)
at C:\Users\lin\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\collection.js:90:37
at Generator.next (<anonymous>)
at asyncGeneratorStep (C:\Users\lin\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\collection.js:22:103)
at _next (C:\Users\lin\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\collection.js:24:194) 
```

**Comment by sunboy166** [comment]
我从昨天到现在一直在下载，还是能用的。。。但是比如我下载20个收藏夹或者关注的人的回答可能下载了13个就会报和你同样的错误，然后我就把下载好的保存到其它地方，然后把那7个没下载的任务的链接再拷贝进去下载。。。。无论专栏 回答 点赞 收藏夹的内容都能下载下来。。感谢作者。

**Comment by sunboy166** [comment]
我用1.0不行 用2.0 第一次打开登录 不行，关了程序重新打开就可以了。。。美滋滋

**Comment by popy32** [comment]
我这边还是不行，推荐 https://github.com/7sDream/zhihu-oauth 这个接口
现在只能写脚本自己跑了

**Comment by YaoZeyuan** [comment]
登录没成功, 卸了重装一次就好了🤣

& 欢迎体验2.3.0 版

https://github.com/YaoZeyuan/zhihuhelp_with_node/releases/tag/2.3.0

**Comment by YaoZeyuan** [comment]
> 我这边还是不行，推荐 https://github.com/7sDream/zhihu-oauth 这个接口
> 现在只能写脚本自己跑了

这个作者已经停更了...
