### ISSUE TITLE
刚刚试了，不行

### ISSUE THREAD

**Issue by edwinyzh** [YaoZeyuan/zhihuhelp_with_node#12]
任务面板运行日志登陆知乎使用说明支持作者
2019-03-05 17:55:48.942: 开始工作 
2019-03-05 17:55:48.946: 任务配置生成完毕 
2019-03-05 17:55:48.947: 重新载入cookie配置 
2019-03-05 17:55:48.948: 开始执行任务 
2019-03-05 17:55:48.949: [DispatchCommand] command start 
2019-03-05 17:55:48.950: [DispatchCommand] 检查更新 
2019-03-05 17:55:48.951: [InitEnv] command start 
2019-03-05 17:55:48.952: [InitEnv] 检查更新 
2019-03-05 17:55:49.261: [InitEnv] 有新版本 
2019-03-05 17:55:49.262: [InitEnv] 请到https://pan.baidu.com/s/1vn-96AlHPKsggSzemVKiEg下载最新版本知乎助手 
2019-03-05 17:55:49.262: [InitEnv] 更新日期:2019年2月18日 
2019-03-05 17:55:49.262: [InitEnv] 更新说明:知乎助手2.1.0版, 闪亮发布. 修复了图片下载失败&无法下载专栏/话题问题 
2019-03-05 17:55:49.263: [InitEnv] command finish 
2019-03-05 17:55:49.263: [FetchAuthor] command start 
2019-03-05 17:55:49.264: [FetchAuthor] 开始抓取用户wang-tao-tao-91-97的数据 
2019-03-05 17:55:49.264: [FetchAuthor] 获取用户信息 
2019-03-05 17:55:49.977: [FetchAuthor] catch error 
2019-03-05 17:55:49.977: [FetchAuthor] Error: SQLITE_ERROR: no such table: Author 
2019-03-05 17:55:49.978: [FetchAuthor] command finish 
2019-03-05 17:55:49.978: [GenerateAuthor] command start 
2019-03-05 17:55:49.979: [GenerateAuthor] 开始抓取用户wang-tao-tao-91-97的数据 
2019-03-05 17:55:49.979: [GenerateAuthor] 获取用户信息 
2019-03-05 17:55:49.984: [GenerateAuthor] 用户信息获取完毕 
2019-03-05 17:55:49.984: [GenerateAuthor] 用户undefined(wang-tao-tao-91-97)共有undefined个回答 
2019-03-05 17:55:49.985: [GenerateAuthor] 删除旧目录 
2019-03-05 17:55:49.985: [GenerateAuthor] 删除旧epub缓存资源目录:D:\Portable_apps\知乎助手\zhihuhelp\resources\app\缓存文件\epub\用户undefined(wang-tao-tao-91-97)的知乎回答集锦 
2019-03-05 17:55:49.990: [GenerateAuthor] 旧epub缓存目录删除完毕 
2019-03-05 17:55:49.991: [GenerateAuthor] 删除旧epub输出资源目录:D:\Portable_apps\知乎助手\zhihuhelp\resources\app\知乎助手输出的电子书\epub\用户undefined(wang-tao-tao-91-97)的知乎回答集锦 
2019-03-05 17:55:49.992: [GenerateAuthor] 旧epub输出目录删除完毕 
2019-03-05 17:55:49.992: [GenerateAuthor] 删除旧html资源目录:D:\Portable_apps\知乎助手\zhihuhelp\resources\app\缓存文件\html\用户undefined(wang-tao-tao-91-97)的知乎回答集锦 
2019-03-05 17:55:49.994: [GenerateAuthor] 旧html资源目录删除完毕 
2019-03-05 17:55:49.994: [GenerateAuthor] 删除旧html输出目录:D:\Portable_apps\知乎助手\zhihuhelp\resources\app\知乎助手输出的电子书\html\用户undefined(wang-tao-tao-91-97)的知乎回答集锦 
2019-03-05 17:55:49.995: [GenerateAuthor] 旧html输出目录删除完毕 
2019-03-05 17:55:49.995: [GenerateAuthor] 创建电子书:用户undefined(wang-tao-tao-91-97)的知乎回答集锦对应文件夹 
2019-03-05 17:55:50.004: [GenerateAuthor] 电子书:用户undefined(wang-tao-tao-91-97)的知乎回答集锦对应文件夹创建完毕 
2019-03-05 17:55:50.014: [GenerateAuthor] 获取回答列表 
2019-03-05 17:55:50.016: [GenerateAuthor] 回答列表获取完毕, 共0条答案 
2019-03-05 17:55:50.016: [GenerateAuthor] catch error 
2019-03-05 17:55:50.017: [GenerateAuthor] TypeError: Cannot read property 'question' of undefined
at Function.generateSingleItemElement (D:\Portable_apps\知乎助手\zhihuhelp\resources\app\dist\view\answer.js:29:73)
at Function.renderInSinglePage (D:\Portable_apps\知乎助手\zhihuhelp\resources\app\dist\view\answer.js:54:34)
at D:\Portable_apps\知乎助手\zhihuhelp\resources\app\dist\command\generate\author.js:94:38
at Generator.next (<anonymous>)
at asyncGeneratorStep (D:\Portable_apps\知乎助手\zhihuhelp\resources\app\dist\command\generate\author.js:24:103)
at _next (D:\Portable_apps\知乎助手\zhihuhelp\resources\app\dist\command\generate\author.js:26:194) 
2019-03-05 17:55:50.017: [GenerateAuthor] command finish 
2019-03-05 17:55:50.017: [DispatchCommand] 执行完毕 
2019-03-05 17:55:50.017: [DispatchCommand] command finish 
2019-03-05 17:55:50.017: 所有任务执行完毕, 打开电子书文件夹 => D:\Portable_apps\知乎助手\zhihuhelp\resources\app\知乎助手输出的电子书 
2019-03-05 17:58:55.821: 开始工作 
2019-03-05 17:58:55.824: 任务配置生成完毕 
2019-03-05 17:58:55.825: 重新载入cookie配置 
2019-03-05 17:58:55.825: 开始执行任务 
2019-03-05 17:58:55.826: [DispatchCommand] command start 
2019-03-05 17:58:55.827: [DispatchCommand] 检查更新 
2019-03-05 17:58:55.828: [InitEnv] command start 
2019-03-05 17:58:55.829: [InitEnv] 检查更新 
2019-03-05 17:58:56.936: [InitEnv] 有新版本 
2019-03-05 17:58:56.937: [InitEnv] 请到https://pan.baidu.com/s/1vn-96AlHPKsggSzemVKiEg下载最新版本知乎助手 
2019-03-05 17:58:56.937: [InitEnv] 更新日期:2019年2月18日 
2019-03-05 17:58:56.937: [InitEnv] 更新说明:知乎助手2.1.0版, 闪亮发布. 修复了图片下载失败&无法下载专栏/话题问题 
2019-03-05 17:58:56.938: [InitEnv] command finish 
2019-03-05 17:58:56.938: [FetchAuthor] command start 
2019-03-05 17:58:56.939: [FetchAuthor] 开始抓取用户wang-tao-tao-91-97的数据 
2019-03-05 17:58:56.939: [FetchAuthor] 获取用户信息 
2019-03-05 17:58:57.480: [FetchAuthor] catch error 
2019-03-05 17:58:57.480: [FetchAuthor] Error: SQLITE_ERROR: no such table: Author 
2019-03-05 17:58:57.480: [FetchAuthor] command finish 
2019-03-05 17:58:57.481: [GenerateAuthor] command start 
2019-03-05 17:58:57.482: [GenerateAuthor] 开始抓取用户wang-tao-tao-91-97的数据 
2019-03-05 17:58:57.482: [GenerateAuthor] 获取用户信息 
2019-03-05 17:58:57.486: [GenerateAuthor] 用户信息获取完毕 
2019-03-05 17:58:57.487: [GenerateAuthor] 用户undefined(wang-tao-tao-91-97)共有undefined个回答 
2019-03-05 17:58:57.488: [GenerateAuthor] 删除旧目录 
2019-03-05 17:58:57.488: [GenerateAuthor] 删除旧epub缓存资源目录:D:\Portable_apps\知乎助手\zhihuhelp\resources\app\缓存文件\epub\用户undefined(wang-tao-tao-91-97)的知乎回答集锦 
2019-03-05 17:58:57.497: [GenerateAuthor] 旧epub缓存目录删除完毕 
2019-03-05 17:58:57.497: [GenerateAuthor] 删除旧epub输出资源目录:D:\Portable_apps\知乎助手\zhihuhelp\resources\app\知乎助手输出的电子书\epub\用户undefined(wang-tao-tao-91-97)的知乎回答集锦 
2019-03-05 17:58:57.498: [GenerateAuthor] 旧epub输出目录删除完毕 
2019-03-05 17:58:57.499: [GenerateAuthor] 删除旧html资源目录:D:\Portable_apps\知乎助手\zhihuhelp\resources\app\缓存文件\html\用户undefined(wang-tao-tao-91-97)的知乎回答集锦 
2019-03-05 17:58:57.501: [GenerateAuthor] 旧html资源目录删除完毕 
2019-03-05 17:58:57.501: [GenerateAuthor] 删除旧html输出目录:D:\Portable_apps\知乎助手\zhihuhelp\resources\app\知乎助手输出的电子书\html\用户undefined(wang-tao-tao-91-97)的知乎回答集锦 
2019-03-05 17:58:57.502: [GenerateAuthor] 旧html输出目录删除完毕 
2019-03-05 17:58:57.503: [GenerateAuthor] 创建电子书:用户undefined(wang-tao-tao-91-97)的知乎回答集锦对应文件夹 
2019-03-05 17:58:57.509: [GenerateAuthor] 电子书:用户undefined(wang-tao-tao-91-97)的知乎回答集锦对应文件夹创建完毕 
2019-03-05 17:58:57.515: [GenerateAuthor] 获取回答列表 
2019-03-05 17:58:57.517: [GenerateAuthor] 回答列表获取完毕, 共0条答案 
2019-03-05 17:58:57.518: [GenerateAuthor] catch error 
2019-03-05 17:58:57.518: [GenerateAuthor] TypeError: Cannot read property 'question' of undefined
at Function.generateSingleItemElement (D:\Portable_apps\知乎助手\zhihuhelp\resources\app\dist\view\answer.js:29:73)
at Function.renderInSinglePage (D:\Portable_apps\知乎助手\zhihuhelp\resources\app\dist\view\answer.js:54:34)
at D:\Portable_apps\知乎助手\zhihuhelp\resources\app\dist\command\generate\author.js:94:38
at Generator.next (<anonymous>)
at asyncGeneratorStep (D:\Portable_apps\知乎助手\zhihuhelp\resources\app\dist\command\generate\author.js:24:103)
at _next (D:\Portable_apps\知乎助手\zhihuhelp\resources\app\dist\command\generate\author.js:26:194) 
2019-03-05 17:58:57.518: [GenerateAuthor] command finish 
2019-03-05 17:58:57.518: [DispatchCommand] 执行完毕 
2019-03-05 17:58:57.519: [DispatchCommand] command finish 
2019-03-05 17:58:57.519: 所有任务执行完毕, 打开电子书文件夹 => D:\Portable_apps\知乎助手\zhihuhelp\resources\app\知乎助手输出的电子书

**Comment by YaoZeyuan** [comment]
2019-03-05 17:55:48.952: [InitEnv] 检查更新
2019-03-05 17:55:49.261: [InitEnv] 有新版本
2019-03-05 17:55:49.262: [InitEnv] 请到https://pan.baidu.com/s/1vn-96AlHPKsggSzemVKiEg下载最新版本知乎助手
2019-03-05 17:55:49.262: [InitEnv] 更新日期:2019年2月18日
2019-03-05 17:55:49.262: [InitEnv] 更新说明:知乎助手2.1.0版, 闪亮发布. 修复了图片下载失败&无法下载专栏/话题问题

更新一下版本啊

**Comment by edwinyzh** [comment]
下载2.1版，可以了，谢谢！
之前因为觉得是从项目主页进入的下载地址，所以觉得按常理这种情况下下载的应该是最新版的，就没注意日志里面的新版提示，哈哈！
非常感谢这个开源项目，让我可以保持一系列非常宝贵的知乎回答！
