### ISSUE TITLE
无法获取个人收藏内容

### ISSUE THREAD

**Issue by ykla** [YaoZeyuan/zhihuhelp_with_node#14]
抓取空白

任务面板运行日志登陆知乎使用说明支持作者
2019-03-14 11:54:38.913: 开始工作 
2019-03-14 11:54:38.928: 任务配置生成完毕 
2019-03-14 11:54:38.929: 重新载入cookie配置 
2019-03-14 11:54:38.931: 开始执行任务 
2019-03-14 11:54:38.933: [DispatchCommand] command start 
2019-03-14 11:54:38.935: [DispatchCommand] 检查更新 
2019-03-14 11:54:38.937: [InitEnv] command start 
2019-03-14 11:54:38.940: [InitEnv] 检查更新 
2019-03-14 11:54:45.210: [InitEnv] 有新版本 
2019-03-14 11:54:45.212: [InitEnv] 请到https://pan.baidu.com/s/1vn-96AlHPKsggSzemVKiEg下载最新版本知乎助手 
2019-03-14 11:54:45.214: [InitEnv] 更新日期:2019年2月18日 
2019-03-14 11:54:45.215: [InitEnv] 更新说明:知乎助手2.1.0版, 闪亮发布. 修复了图片下载失败&无法下载专栏/话题问题 
2019-03-14 11:54:45.217: [InitEnv] command finish 
2019-03-14 11:54:45.218: [DispatchCommand] 执行完毕 
2019-03-14 11:54:45.219: [DispatchCommand] command finish 
2019-03-14 11:54:45.220: 所有任务执行完毕, 打开电子书文件夹 => C:\Program Files\zhihuhelp\resources\app\知乎助手输出的电子书 
2019-03-14 11:57:49.006: 开始工作 
2019-03-14 11:57:49.018: 任务配置生成完毕 
2019-03-14 11:57:49.019: 重新载入cookie配置 
2019-03-14 11:57:49.023: 开始执行任务 
2019-03-14 11:57:49.025: [DispatchCommand] command start 
2019-03-14 11:57:49.027: [DispatchCommand] 检查更新 
2019-03-14 11:57:49.031: [InitEnv] command start 
2019-03-14 11:57:49.034: [InitEnv] 检查更新 
2019-03-14 11:57:54.180: [InitEnv] 有新版本 
2019-03-14 11:57:54.182: [InitEnv] 请到https://pan.baidu.com/s/1vn-96AlHPKsggSzemVKiEg下载最新版本知乎助手 
2019-03-14 11:57:54.183: [InitEnv] 更新日期:2019年2月18日 
2019-03-14 11:57:54.183: [InitEnv] 更新说明:知乎助手2.1.0版, 闪亮发布. 修复了图片下载失败&无法下载专栏/话题问题 
2019-03-14 11:57:54.184: [InitEnv] command finish 
2019-03-14 11:57:54.185: [FetchCollection] command start 
2019-03-14 11:57:54.186: [FetchCollection] 开始抓取收藏夹内的回答 
2019-03-14 11:57:54.187: [FetchCollection] 获取收藏夹信息 
2019-03-14 11:57:54.546: [FetchCollection] catch error 
2019-03-14 11:57:54.547: [FetchCollection] Error: SQLITE_ERROR: no such table: Collection 
2019-03-14 11:57:54.549: [FetchCollection] command finish 
2019-03-14 11:57:54.552: [GenerateCollection] command start 
2019-03-14 11:57:54.555: [GenerateCollection] 开始抓取收藏夹的信息 
2019-03-14 11:57:54.569: [GenerateCollection] 收藏夹信息获取完毕 
2019-03-14 11:57:54.570: [GenerateCollection] 收藏夹undefined()内共有undefined条回答 
2019-03-14 11:57:54.571: [GenerateCollection] 删除旧目录 
2019-03-14 11:57:54.572: [GenerateCollection] 删除旧epub缓存资源目录:C:\Program Files\zhihuhelp\resources\app\缓存文件\epub\收藏夹undefined()下知乎回答集锦 
2019-03-14 11:57:54.580: [GenerateCollection] 旧epub缓存目录删除完毕 
2019-03-14 11:57:54.581: [GenerateCollection] 删除旧epub输出资源目录:C:\Program Files\zhihuhelp\resources\app\知乎助手输出的电子书\epub\收藏夹undefined()下知乎回答集锦 
2019-03-14 11:57:54.583: [GenerateCollection] 旧epub输出目录删除完毕 
2019-03-14 11:57:54.584: [GenerateCollection] 删除旧html资源目录:C:\Program Files\zhihuhelp\resources\app\缓存文件\html\收藏夹undefined()下知乎回答集锦 
2019-03-14 11:57:54.585: [GenerateCollection] 旧html资源目录删除完毕 
2019-03-14 11:57:54.586: [GenerateCollection] 删除旧html输出目录:C:\Program Files\zhihuhelp\resources\app\知乎助手输出的电子书\html\收藏夹undefined()下知乎回答集锦 
2019-03-14 11:57:54.587: [GenerateCollection] 旧html输出目录删除完毕 
2019-03-14 11:57:54.588: [GenerateCollection] 创建电子书:收藏夹undefined()下知乎回答集锦对应文件夹 
2019-03-14 11:57:54.609: [GenerateCollection] 电子书:收藏夹undefined()下知乎回答集锦对应文件夹创建完毕 
2019-03-14 11:57:54.626: [GenerateCollection] 获取回答列表 
2019-03-14 11:57:54.630: [GenerateCollection] 回答列表获取完毕, 共0条答案 
2019-03-14 11:57:54.631: [GenerateCollection] catch error 
2019-03-14 11:57:54.632: [GenerateCollection] TypeError: Cannot read property 'question' of undefined
at Function.generateSingleItemElement (C:\Program Files\zhihuhelp\resources\app\dist\view\answer.js:29:73)
at Function.renderInSinglePage (C:\Program Files\zhihuhelp\resources\app\dist\view\answer.js:54:34)
at C:\Program Files\zhihuhelp\resources\app\dist\command\generate\collection.js:90:37
at Generator.next (<anonymous>)
at asyncGeneratorStep (C:\Program Files\zhihuhelp\resources\app\dist\command\generate\collection.js:22:103)
at _next (C:\Program Files\zhihuhelp\resources\app\dist\command\generate\collection.js:24:194) 
2019-03-14 11:57:54.632: [GenerateCollection] command finish 
2019-03-14 11:57:54.633: [DispatchCommand] 执行完毕 
2019-03-14 11:57:54.633: [DispatchCommand] command finish 
2019-03-14 11:57:54.634: 所有任务执行完毕, 打开电子书文件夹 => C:\Program Files\zhihuhelp\resources\app\知乎助手输出的电子书 
2019-03-14 11:59:35.852: 开始工作 
2019-03-14 11:59:35.862: 任务配置生成完毕 
2019-03-14 11:59:35.863: 重新载入cookie配置 
2019-03-14 11:59:35.867: 开始执行任务 
2019-03-14 11:59:35.869: [DispatchCommand] command start 
2019-03-14 11:59:35.872: [DispatchCommand] 检查更新 
2019-03-14 11:59:35.876: [InitEnv] command start 
2019-03-14 11:59:35.880: [InitEnv] 检查更新 
2019-03-14 11:59:36.002: [InitEnv] 有新版本 
2019-03-14 11:59:36.002: [InitEnv] 请到https://pan.baidu.com/s/1vn-96AlHPKsggSzemVKiEg下载最新版本知乎助手 
2019-03-14 11:59:36.003: [InitEnv] 更新日期:2019年2月18日 
2019-03-14 11:59:36.004: [InitEnv] 更新说明:知乎助手2.1.0版, 闪亮发布. 修复了图片下载失败&无法下载专栏/话题问题 
2019-03-14 11:59:36.004: [InitEnv] command finish 
2019-03-14 11:59:36.005: [FetchCollection] command start 
2019-03-14 11:59:36.005: [FetchCollection] 开始抓取收藏夹270763413内的回答 
2019-03-14 11:59:36.006: [FetchCollection] 获取收藏夹信息 
2019-03-14 11:59:36.436: [FetchCollection] catch error 
2019-03-14 11:59:36.437: [FetchCollection] Error: SQLITE_ERROR: no such table: Collection 
2019-03-14 11:59:36.438: [FetchCollection] command finish 
2019-03-14 11:59:36.439: [GenerateCollection] command start 
2019-03-14 11:59:36.440: [GenerateCollection] 开始抓取收藏夹270763413的信息 
2019-03-14 11:59:36.443: [GenerateCollection] 收藏夹信息获取完毕 
2019-03-14 11:59:36.444: [GenerateCollection] 收藏夹undefined(270763413)内共有undefined条回答 
2019-03-14 11:59:36.444: [GenerateCollection] 删除旧目录 
2019-03-14 11:59:36.445: [GenerateCollection] 删除旧epub缓存资源目录:C:\Program Files\zhihuhelp\resources\app\缓存文件\epub\收藏夹undefined(270763413)下知乎回答集锦 
2019-03-14 11:59:36.447: [GenerateCollection] 旧epub缓存目录删除完毕 
2019-03-14 11:59:36.447: [GenerateCollection] 删除旧epub输出资源目录:C:\Program Files\zhihuhelp\resources\app\知乎助手输出的电子书\epub\收藏夹undefined(270763413)下知乎回答集锦 
2019-03-14 11:59:36.448: [GenerateCollection] 旧epub输出目录删除完毕 
2019-03-14 11:59:36.449: [GenerateCollection] 删除旧html资源目录:C:\Program Files\zhihuhelp\resources\app\缓存文件\html\收藏夹undefined(270763413)下知乎回答集锦 
2019-03-14 11:59:36.450: [GenerateCollection] 旧html资源目录删除完毕 
2019-03-14 11:59:36.451: [GenerateCollection] 删除旧html输出目录:C:\Program Files\zhihuhelp\resources\app\知乎助手输出的电子书\html\收藏夹undefined(270763413)下知乎回答集锦 
2019-03-14 11:59:36.452: [GenerateCollection] 旧html输出目录删除完毕 
2019-03-14 11:59:36.453: [GenerateCollection] 创建电子书:收藏夹undefined(270763413)下知乎回答集锦对应文件夹 
2019-03-14 11:59:36.468: [GenerateCollection] 电子书:收藏夹undefined(270763413)下知乎回答集锦对应文件夹创建完毕 
2019-03-14 11:59:36.482: [GenerateCollection] 获取回答列表 
2019-03-14 11:59:36.485: [GenerateCollection] 回答列表获取完毕, 共0条答案 
2019-03-14 11:59:36.486: [GenerateCollection] catch error 
2019-03-14 11:59:36.487: [GenerateCollection] TypeError: Cannot read property 'question' of undefined
at Function.generateSingleItemElement (C:\Program Files\zhihuhelp\resources\app\dist\view\answer.js:29:73)
at Function.renderInSinglePage (C:\Program Files\zhihuhelp\resources\app\dist\view\answer.js:54:34)
at C:\Program Files\zhihuhelp\resources\app\dist\command\generate\collection.js:90:37
at Generator.next (<anonymous>)
at asyncGeneratorStep (C:\Program Files\zhihuhelp\resources\app\dist\command\generate\collection.js:22:103)
at _next (C:\Program Files\zhihuhelp\resources\app\dist\command\generate\collection.js:24:194) 
2019-03-14 11:59:36.487: [GenerateCollection] command finish 
2019-03-14 11:59:36.488: [DispatchCommand] 执行完毕 
2019-03-14 11:59:36.488: [DispatchCommand] command finish 
2019-03-14 11:59:36.489: 所有任务执行完毕, 打开电子书文件夹 => C:\Program Files\zhihuhelp\resources\app\知乎助手输出的电子书 
2019-03-14 12:00:53.841: 开始工作 
2019-03-14 12:00:53.852: 任务配置生成完毕 
2019-03-14 12:00:53.854: 重新载入cookie配置 
2019-03-14 12:00:53.858: 开始执行任务 
2019-03-14 12:00:53.861: [DispatchCommand] command start 
2019-03-14 12:00:53.863: [DispatchCommand] 检查更新 
2019-03-14 12:00:53.865: [InitEnv] command start 
2019-03-14 12:00:53.867: [InitEnv] 检查更新 
2019-03-14 12:00:53.997: [InitEnv] 有新版本 
2019-03-14 12:00:53.999: [InitEnv] 请到https://pan.baidu.com/s/1vn-96AlHPKsggSzemVKiEg下载最新版本知乎助手 
2019-03-14 12:00:54.001: [InitEnv] 更新日期:2019年2月18日 
2019-03-14 12:00:54.003: [InitEnv] 更新说明:知乎助手2.1.0版, 闪亮发布. 修复了图片下载失败&无法下载专栏/话题问题 
2019-03-14 12:00:54.005: [InitEnv] command finish 
2019-03-14 12:00:54.007: [FetchCollection] command start 
2019-03-14 12:00:54.009: [FetchCollection] 开始抓取收藏夹270763413内的回答 
2019-03-14 12:00:54.010: [FetchCollection] 获取收藏夹信息 
2019-03-14 12:00:54.468: [FetchCollection] catch error 
2019-03-14 12:00:54.469: [FetchCollection] Error: SQLITE_ERROR: no such table: Collection 
2019-03-14 12:00:54.470: [FetchCollection] command finish 
2019-03-14 12:00:54.471: [GenerateCollection] command start 
2019-03-14 12:00:54.472: [GenerateCollection] 开始抓取收藏夹270763413的信息 
2019-03-14 12:00:54.476: [GenerateCollection] 收藏夹信息获取完毕 
2019-03-14 12:00:54.477: [GenerateCollection] 收藏夹undefined(270763413)内共有undefined条回答 
2019-03-14 12:00:54.478: [GenerateCollection] 删除旧目录 
2019-03-14 12:00:54.479: [GenerateCollection] 删除旧epub缓存资源目录:C:\Program Files\zhihuhelp\resources\app\缓存文件\epub\收藏夹undefined(270763413)下知乎回答集锦 
2019-03-14 12:00:54.497: [GenerateCollection] 旧epub缓存目录删除完毕 
2019-03-14 12:00:54.498: [GenerateCollection] 删除旧epub输出资源目录:C:\Program Files\zhihuhelp\resources\app\知乎助手输出的电子书\epub\收藏夹undefined(270763413)下知乎回答集锦 
2019-03-14 12:00:54.501: [GenerateCollection] 旧epub输出目录删除完毕 
2019-03-14 12:00:54.502: [GenerateCollection] 删除旧html资源目录:C:\Program Files\zhihuhelp\resources\app\缓存文件\html\收藏夹undefined(270763413)下知乎回答集锦 
2019-03-14 12:00:54.515: [GenerateCollection] 旧html资源目录删除完毕 
2019-03-14 12:00:54.516: [GenerateCollection] 删除旧html输出目录:C:\Program Files\zhihuhelp\resources\app\知乎助手输出的电子书\html\收藏夹undefined(270763413)下知乎回答集锦 
2019-03-14 12:00:54.519: [GenerateCollection] 旧html输出目录删除完毕 
2019-03-14 12:00:54.519: [GenerateCollection] 创建电子书:收藏夹undefined(270763413)下知乎回答集锦对应文件夹 
2019-03-14 12:00:54.534: [GenerateCollection] 电子书:收藏夹undefined(270763413)下知乎回答集锦对应文件夹创建完毕 
2019-03-14 12:00:54.547: [GenerateCollection] 获取回答列表 
2019-03-14 12:00:54.549: [GenerateCollection] 回答列表获取完毕, 共0条答案 
2019-03-14 12:00:54.550: [GenerateCollection] catch error 
2019-03-14 12:00:54.551: [GenerateCollection] TypeError: Cannot read property 'question' of undefined
at Function.generateSingleItemElement (C:\Program Files\zhihuhelp\resources\app\dist\view\answer.js:29:73)
at Function.renderInSinglePage (C:\Program Files\zhihuhelp\resources\app\dist\view\answer.js:54:34)
at C:\Program Files\zhihuhelp\resources\app\dist\command\generate\collection.js:90:37
at Generator.next (<anonymous>)
at asyncGeneratorStep (C:\Program Files\zhihuhelp\resources\app\dist\command\generate\collection.js:22:103)
at _next (C:\Program Files\zhihuhelp\resources\app\dist\command\generate\collection.js:24:194) 
2019-03-14 12:00:54.551: [GenerateCollection] command finish 
2019-03-14 12:00:54.552: [DispatchCommand] 执行完毕 
2019-03-14 12:00:54.553: [DispatchCommand] command finish 
2019-03-14 12:00:54.554: 所有任务执行完毕, 打开电子书文件夹 => C:\Program Files\zhihuhelp\resources\app\知乎助手输出的电子书 
2019-03-14 12:02:34.212: 开始工作 
2019-03-14 12:02:34.218: 任务配置生成完毕 
2019-03-14 12:02:34.219: 重新载入cookie配置 
2019-03-14 12:02:34.220: 开始执行任务 
2019-03-14 12:02:34.221: [DispatchCommand] command start 
2019-03-14 12:02:34.222: [DispatchCommand] 检查更新 
2019-03-14 12:02:34.224: [InitEnv] command start 
2019-03-14 12:02:34.225: [InitEnv] 检查更新 
2019-03-14 12:02:34.717: [InitEnv] 有新版本 
2019-03-14 12:02:34.719: [InitEnv] 请到https://pan.baidu.com/s/1vn-96AlHPKsggSzemVKiEg下载最新版本知乎助手 
2019-03-14 12:02:34.720: [InitEnv] 更新日期:2019年2月18日 
2019-03-14 12:02:34.721: [InitEnv] 更新说明:知乎助手2.1.0版, 闪亮发布. 修复了图片下载失败&无法下载专栏/话题问题 
2019-03-14 12:02:34.722: [InitEnv] command finish 
2019-03-14 12:02:34.723: [FetchCollection] command start 
2019-03-14 12:02:34.724: [FetchCollection] 开始抓取收藏夹270763413内的回答 
2019-03-14 12:02:34.725: [FetchCollection] 获取收藏夹信息 
2019-03-14 12:02:35.742: [FetchCollection] catch error 
2019-03-14 12:02:35.743: [FetchCollection] Error: SQLITE_ERROR: no such table: Collection 
2019-03-14 12:02:35.744: [FetchCollection] command finish 
2019-03-14 12:02:35.744: [GenerateCollection] command start 
2019-03-14 12:02:35.745: [GenerateCollection] 开始抓取收藏夹270763413的信息 
2019-03-14 12:02:35.748: [GenerateCollection] 收藏夹信息获取完毕 
2019-03-14 12:02:35.749: [GenerateCollection] 收藏夹undefined(270763413)内共有undefined条回答 
2019-03-14 12:02:35.750: [GenerateCollection] 删除旧目录 
2019-03-14 12:02:35.750: [GenerateCollection] 删除旧epub缓存资源目录:C:\Program Files\zhihuhelp\resources\app\缓存文件\epub\收藏夹undefined(270763413)下知乎回答集锦 
2019-03-14 12:02:35.760: [GenerateCollection] 旧epub缓存目录删除完毕 
2019-03-14 12:02:35.760: [GenerateCollection] 删除旧epub输出资源目录:C:\Program Files\zhihuhelp\resources\app\知乎助手输出的电子书\epub\收藏夹undefined(270763413)下知乎回答集锦 
2019-03-14 12:02:35.762: [GenerateCollection] 旧epub输出目录删除完毕 
2019-03-14 12:02:35.763: [GenerateCollection] 删除旧html资源目录:C:\Program Files\zhihuhelp\resources\app\缓存文件\html\收藏夹undefined(270763413)下知乎回答集锦 
2019-03-14 12:02:35.771: [GenerateCollection] 旧html资源目录删除完毕 
2019-03-14 12:02:35.771: [GenerateCollection] 删除旧html输出目录:C:\Program Files\zhihuhelp\resources\app\知乎助手输出的电子书\html\收藏夹undefined(270763413)下知乎回答集锦 
2019-03-14 12:02:35.774: [GenerateCollection] 旧html输出目录删除完毕 
2019-03-14 12:02:35.774: [GenerateCollection] 创建电子书:收藏夹undefined(270763413)下知乎回答集锦对应文件夹 
2019-03-14 12:02:35.787: [GenerateCollection] 电子书:收藏夹undefined(270763413)下知乎回答集锦对应文件夹创建完毕 
2019-03-14 12:02:35.799: [GenerateCollection] 获取回答列表 
2019-03-14 12:02:35.803: [GenerateCollection] 回答列表获取完毕, 共0条答案 
2019-03-14 12:02:35.803: [GenerateCollection] catch error 
2019-03-14 12:02:35.804: [GenerateCollection] TypeError: Cannot read property 'question' of undefined
at Function.generateSingleItemElement (C:\Program Files\zhihuhelp\resources\app\dist\view\answer.js:29:73)
at Function.renderInSinglePage (C:\Program Files\zhihuhelp\resources\app\dist\view\answer.js:54:34)
at C:\Program Files\zhihuhelp\resources\app\dist\command\generate\collection.js:90:37
at Generator.next (<anonymous>)
at asyncGeneratorStep (C:\Program Files\zhihuhelp\resources\app\dist\command\generate\collection.js:22:103)
at _next (C:\Program Files\zhihuhelp\resources\app\dist\command\generate\collection.js:24:194) 
2019-03-14 12:02:35.805: [GenerateCollection] command finish 
2019-03-14 12:02:35.805: [DispatchCommand] 执行完毕 
2019-03-14 12:02:35.806: [DispatchCommand] command finish 
2019-03-14 12:02:35.806: 所有任务执行完毕, 打开电子书文件夹 => C:\Program Files\zhihuhelp\resources\app\知乎助手输出的电子书

**Comment by ykla** [comment]
页面指向旧版本，请修复

**Comment by ykla** [comment]
默认1.0.0

**Comment by YaoZeyuan** [comment]
done 

https://github.com/YaoZeyuan/zhihuhelp_with_node/releases/tag/2.3.0
