### ISSUE TITLE
Windows版本部分接口失效

### ISSUE THREAD

**Issue by popy32** [YaoZeyuan/zhihuhelp_with_node#9]
感谢开发者
目前只有 指定知乎用户的全部回答 指定知乎用户赞同过的全部回答&文章 可以使用

特殊 用户名 解析失效 例如 https://www.zhihu.com/org/shen-me-zhi-de-mai-76-83/activities

抓取 话题 失败 例如 https://www.zhihu.com/topic/19668796/hot

```bash
2019-02-22 12:13:01.712: [GenerateTopic] 旧html输出目录删除完毕 
2019-02-22 12:13:01.713: [GenerateTopic] 创建电子书:话题社保基金(19668796)下精华回答集锦对应文件夹 
2019-02-22 12:13:01.727: [GenerateTopic] 电子书:话题社保基金(19668796)下精华回答集锦对应文件夹创建完毕 
2019-02-22 12:13:01.735: [GenerateTopic] 获取话题答案列表 
2019-02-22 12:13:01.741: [GenerateTopic] 话题答案列表获取完毕, 共10条答案 
2019-02-22 12:13:01.745: [GenerateTopic] catch error 
2019-02-22 12:13:01.746: [GenerateTopic] TypeError: Cannot read property 'title' of undefined
at Function.render (C:\Users\lin\AppData\Local\Programs\zhihuhelp\resources\app\dist\view\answer.js:37:43)
at C:\Users\lin\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\topic.js:80:39
at Generator.next (<anonymous>)
at asyncGeneratorStep (C:\Users\lin\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\topic.js:22:103)
at _next (C:\Users\lin\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\topic.js:24:194) 
2019-02-22 12:13:01.746: [GenerateTopic] command finish 
2019-02-22 12:13:01.747: [DispatchCommand] 执行完毕 
2019-02-22 12:13:01.747: [DispatchCommand] command finish 
2019-02-22 12:13:01.747: 所有任务执行完毕, 打开电子书文件夹 => C:\Users\lin\AppData\Local\Programs\zhihuhelp\resources\app\知乎助手输出的电子书 
2019-02-22 12:13:03.279: [FetchTopic] 第0~10条精华回答抓取完毕 
```

专栏下载失败 https://zhuanlan.zhihu.com/yyln2016

```bash
2019-02-22 12:16:53.618: [GenerateColumn] 创建电子书:专栏undefined(yyln2016)的知乎文章集锦对应文件夹 
2019-02-22 12:16:53.628: [GenerateColumn] 电子书:专栏undefined(yyln2016)的知乎文章集锦对应文件夹创建完毕 
2019-02-22 12:16:53.636: [GenerateColumn] 获取文章列表 
2019-02-22 12:16:53.638: [GenerateColumn] 文章列表获取完毕, 共0条答案 
2019-02-22 12:16:53.640: [GenerateColumn] 内容渲染完毕, 开始对内容进行输出前预处理 
2019-02-22 12:16:53.645: [GenerateColumn] 内容列表预处理完毕, 准备下载图片 
2019-02-22 12:16:53.645: [GenerateColumn] 开始下载图片, 共0张待下载 
2019-02-22 12:16:53.646: [GenerateColumn] 清空任务队列 
2019-02-22 12:16:53.646: 任务队列已满, 开始执行任务, 共16个任务待执行 
2019-02-22 12:16:53.647: [GenerateColumn] catch error 
2019-02-22 12:16:53.647: [GenerateColumn] Error: ENOENT: no such file or directory, open 'C:\Users\lin\AppData\Local\Programs\zhihuhelp\resources\app\缓存文件\imgPool\equation？tex＝％5Cbegin％7Baligned％7D＋％CF％83＋％26％3D＋％2812345％29％28678％29＋％26％26％E2％88％88＋S_8＋％5C％5C＋v％26％3D＋％281％2C＋0％2C＋0％2C＋0％2C＋0％2C＋0％2C＋0％2C＋0％2C＋2％29％26％26％E2％88％88％28％5Cmathbb％7BZ％7D％2F3％29％5E8％5C％5C＋％CF％84％26％3D％281234567％29％2889％29％2810＋11％29＋％26％26％E2％88％88＋S_％7B12％7D％5C％5C＋u＋％26％3D＋％281％2C＋0％2C＋0％2C＋0％2C＋0％2C＋0％2C＋0％2C＋1％2C＋0％2C＋0％2C＋0％2C＋0％29＋％26％26％E2％88％88＋％28％5Cmathbb％7BZ％7D％2F2％29％5E％7B12％7D＋％5Cend％7Baligned％7D'
at Object.openSync (fs.js:436:3)
at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)
at Object.writeFileSync (fs.js:1168:35)
at C:\Users\lin\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\base.js:277:25
at Generator.next (<anonymous>)
at asyncGeneratorStep (C:\Users\lin\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\base.js:32:103)
at _next (C:\Users\lin\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\base.js:34:194) 
2019-02-22 12:16:53.647: [GenerateColumn] command finish 
2019-02-22 12:16:53.648: [DispatchCommand] 执行完毕 
2019-02-22 12:16:53.648: [DispatchCommand] command finish 
2019-02-22 12:16:53.648: 所有任务执行完毕, 打开电子书文件夹 => C:\Users\lin\AppData\Local\Programs\zhihuhelp\resources\app\知乎助手输出的电子书
```

**Comment by popy32** [comment]
知乎助手-2.1.0-安装包.zip
https://pan.baidu.com/s/1vn-96AlHPKsggSzemVKiEg
